spring:
  application:
    name: micro-oauth2-auth
#  profiles:
#    active: dev
#  main:
#    banner_mode: 'off'

server:
  port: 9401

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true

keycloak:
  # 表示是一个public的client
  public-client: true
  # keycloak的地址
  auth-server-url: http://localhost:8080/auth
  # keycloak中的realm
  realm: book-service
  resource: service-user
#  ssl-required: external
  securityConstraints:
    - authRoles:
        # 以下路径需要user角色才能访问
        - user
      securityCollections:
        # name可以随便写
        - name: user-role-mappings
          patterns:
            - /secure/user
    - authRoles:
        - admin
      securityCollections:
        - name: admin-roles
          patterns:
            - /secure/admin

logging:
  level.org.keycloak: DEBUG
  level.org.apache.catalina.authenticator: DEBUG
  level.de.ctrlaltdel: DEBUG