spring:
  application:
    name: API-GATEWAY
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      metrics:
        enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: CONSUMER
          uri: lb://CONSUMER
#          uri: http://localhost:8081/consumer
          predicates:
            - Path=/api/**
#          predicates:
#            - Path=/api/**
#          filters:
#            - RewritePath=/api/(?<segment>.*), /consumer/$\{segment}
            #        - id: SHOPPING-CART-SERVICE
            #          uri: lb://SHOPPING-CART-SERVICE
            #          predicates:
            #            - Path=/api/cart/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/product_service
        registration:
          spring-gateway:
            authorization-grant-type: authorization_code
            client-id: spring-gateway
            client-secret: 323ad3d5-b881-4204-8151-d96823077af0
            provider: keycloak
#            redirect-uri: http://localhost:8080/login/oauth2/code/spring-gateway
            redirect-uri: http://localhost:8080/#/dashboard
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/auth/realms/product_service/protocol/openid-connect/certs

server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
      
