

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: Consumer-8081
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8081