

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: Consumer-8081
    hostname: localhost
    prefer-ip-address: true
server:
  port: 8081

spring:
  application:
    name: CONSUMER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      name: customerTopic